#this is for node UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: philippaul/node-mongo-db:04
          #ensures that when we run the deployment and service file the values mentioned are provided to the index file
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: myservice-node-app
spec:
  selector:
    app: node-app
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  type: LoadBalancer
